### PR TITLE
Fix unintended variable shadowing

### PR DESCRIPTION
**Pull request by davidcassany**
It fixes is an embarrassing mistake I did. This issue shouldn't have ever escaped my radar.

### CODE REVIEW

**Comment by davidcassany** [comment]
@nkubala a gentle ping for an easy-to-do review

**Comment by davidcassany** [comment]
@dlorenc thanks! :+1:

**Comment by nkubala** [comment]
@davidcassany so sorry I missed this review...Github notifications strike again 😢

**Comment by davidcassany** [comment]
> so sorry I missed this review...Github notifications strike again

No problem ;)

**Comment by davidcassany** [comment]
@nkubala would it be possible to make a new minor release including last couple merges in master? I'd like to include them in the openSUSE contiainer-diff package and having it tagged in version is helpful for the Open Build Service.

**Comment by nkubala** [comment]
@davidcassany definitely, I'll do one today.

**Pull request merged**
