### PR TITLE
Report differences in mod time & file mod bits when diffing files

### PR DESCRIPTION
**Pull request by smukherj1**
I would like to see if this change makes sense. If so, please let me know what tests I should add and where

### CODE REVIEW

**Comment by smukherj1** [comment]
This fixes #308

**Comment by smukherj1** [comment]
I think reporting differences in the modification time should be made optional

**Comment by smukherj1** [comment]
Also, it seems when I test this, the reported mtime is the time the files were locally extracted at by container-diff instead of the mtime of the files in the images themselves

**Comment by nkubala** [comment]
@smukherj1 is this PR still active? if so, can you try and get CI passing?

**Comment by smukherj1** [comment]
Yeah not really working on this anymore.

**Pull request closed without merging**
