### PR TITLE
add -k arg for keeping the image filesystem owner

### PR DESCRIPTION
**Pull request by zrss**
Fixes: #276 

thoughts ?

and if u tend to keep the owner, u should run the cmd with root permission (or just a root user) as the owner maybe missing in your host

### CODE REVIEW

**Comment by zrss** [comment]
/assign @aaron-prindle 

hi aaron-prindle, thx for the great tool, currently i use it to recover the container root fs to do some security validation. yeah, i encounter the case, i have to check the newly added file should not be uid 0 (root user)

so i open a PR for improving it, if that have some benefits, could u have time for help me tune it better.

or any idea to solve my problem

**Comment by aaron-prindle** [comment]
Hi @zrss, thanks for the PR!  The code looks good, do you think you could add a section for the flag in the README.md here: https://github.com/GoogleContainerTools/container-diff#other-flags

Thanks for adding this!

**Comment by zrss** [comment]
@aaron-prindle , thanks for the reply. 😅 , and i still got stuck at some cases ... still working on it

**Comment by nkubala** [comment]
@zrss is this PR still active?

**Pull request closed without merging**
