### PR TITLE
Remove unnecessary flag parsing

### LINKED ISSUE #306: [bug] --help doesn't print entire output
With the latest release, `container-diff --help` doesn't print anything as it should (see https://github.com/GoogleContainerTools/container-diff/issues/301#issuecomment-478742411)

### Expected behavior

```bash
container-diff --help
container-diff is a CLI tool for analyzing and comparing container images.

Images can be specified from either a local Docker daemon, or from a remote registry.
To specify a local image, prefix the image ID with 'daemon://', e.g. 'daemon://gcr.io/foo/bar'.
To specify a remote image, prefix the image ID with 'remote://', e.g. 'remote://gcr.io/foo/bar'.
If no prefix is specified, the local daemon will be checked first.

Tarballs can also be specified by simply providing the path to the .tar, .tar.gz, or .tgz file.

Usage:
  container-diff [command]

Available Commands:
  analyze     Analyzes an image: [image]
  diff        Compare two images: [image1] [image2]
  help        Help about any command
  version     Print the version of container-diff

Flags:
      --format string      Format to output diff in.
  -h, --help               help for container-diff
  -v, --verbosity string   This flag controls the verbosity of container-diff. (default "warning")

Use "container-diff [command] --help" for more information about a command.
```

### Actual behavior
```bash
$ container-diff --help
Usage of container-diff:
```
### Information
- OS: Tested on ubuntu 18.04, 16.04, and archlinx (see issue linked above)
- container-diff version: v0.15.0

### Steps to reproduce the behavior
 Install container-diff as specific for linux in the README.md, and then run `container-diff --help`.

### PR DESCRIPTION
**Pull request by lplazas**
Fixes #306 

Please let me know if I am missing something (first project contribution). While debugging this issue I found out that because cobra is being used, the flags are being parsed using [pflag](https://github.com/spf13/pflag) automatically in the back, which makes it unnecessary to make the Parse function call ourselves. 
Additionally, the call I removed was being made to the standard go _flags_ library, which doesn't contain any of the cobra flags configuration, reason why the default help output logged was empty.

### CODE REVIEW

**Comment by lplazas** [comment]
@googlebot I signed it!

**Comment by vsoch** [comment]
okay, I'm not able to officially review, but here is my testing! First, this is a freshly pulled master branch. The current behavior for the help command:

```bash
$ ./out/container-diff --help
Usage of ./out/container-diff:
```
This confirms reproducing #306. Now I'm going to test the fixes in @lplazas branch.

```bash
$ ./out/container-diff --help
container-diff is a CLI tool for analyzing and comparing container images.

Images can be specified from either a local Docker daemon, or from a remote registry.
To specify a local image, prefix the image ID with 'daemon://', e.g. 'daemon://gcr.io/foo/bar'.
To specify a remote image, prefix the image ID with 'remote://', e.g. 'remote://gcr.io/foo/bar'.
If no prefix is specified, the local daemon will be checked first.

Tarballs can also be specified by simply providing the path to the .tar, .tar.gz, or .tgz file.

Usage:
  container-diff [command]

Available Commands:
  analyze     Analyzes an image: container-diff image
  diff        Compare two images: container-diff image1 image2
  help        Help about any command
  version     Print the version of container-diff

Flags:
      --format string                             Format to output diff in.
  -h, --help                                      help for container-diff
      --registry-certificate keyValueFlag         Use the provided certificate for TLS communication with the given registry. Expected format is 'my.registry=/path/to/the/server/certificate'.
      --skip-tls-verify-registry multiValueFlag   Insecure registry ignoring TLS verify to push and pull. Set it repeatedly for multiple registries.
  -v, --verbosity string                          This flag controls the verbosity of container-diff. (default "warning")

Use "container-diff [command] --help" for more information about a command.
```
Tada! We have help! So superficially, this fixes the issue that I opened previously.

**Comment by lplazas** [comment]
Thanks for your review @vsoch. It felt kind of incomplete without any type of testing, so I just added some unit tests to make sure it works as expected and that the other help functionality didn't break.

**Comment by vsoch** [comment]
This will be very sensitive to subtle changes in help strings, and slight differences in how a result might be printed for a particular console. I think it's up to the maintainers to decide on the level of detail that is warranted here, because it could become burdensome to need to update the help string tests any time a change to the text is done. But regardless, always good thinking to add a test.

**Comment by lplazas** [comment]
I agree, it might get annoying to always change the text for the devs, although as this project is in maintenance mode I don't think it will get a lot of changes in the future. 
I just changed the expected output to not depend on the way the text is formatted, so I just included the messages themselves instead of the entire line with spaces included.

**Pull request merged**
