### PR TITLE
Fix local repo paths in contributor guidance.

### PR DESCRIPTION
**Pull request by deorbit**
Configuring the repository will fail with the given paths (will clone into $GOPATH/src/github.com/GoogleContainerTools, subsequent ```cd``` and ```git remote add``` will fail).

### CODE REVIEW

**Comment by deorbit** [comment]
CLA signed and sealed.

**Comment by deorbit** [comment]
With my previous commit, import paths won't work, so I've changed guidance further to clone into $GOPATH/src/github.com/GoogleContainerTools and set the contributor's repo as a remote there as suggested by @campoy.

**Comment by nkubala** [comment]
The reason this didn't work originally is because we were missing the last part of the directory path in the `git clone` line:

```
git clone git@github.com:<your_account>/container-diff.git
$GOPATH/src/github.com/GoogleContainerTools
```
should be
```
git clone git@github.com:<your_account>/container-diff.git
$GOPATH/src/github.com/GoogleContainerTools/container-diff
```

That should make the flow we were trying to specify work, could you just update the original clone path?

**Comment by deorbit** [comment]
@nkubala Makes sense! I've cleaned up the branch this PR came from and issued PR #255 under a new branch of my fork.

**Pull request closed without merging**
