### PR TITLE
Extract to tmpdir without characters that are illegal on Windows

### LINKED ISSUE #394: Windows: fails to create TempDir
I'm running https://github.com/GoogleContainerTools/container-structure-test/blob/main/bazel/test/BUILD.bazel#L3-L8 on Windows, and it fails.

### Expected behavior
Should get the image name from a tar on Windows.

### Actual behavior

```
+ exec C:/users/alex/_bazel_alex/urhld3y7/external/cst_st_windows_amd64/structure_test test --driver tar --image C:/users/alex/documents/github/container-structure-test/bazel/test/tarball.tar --config C:/users/alex/documents/github/container-structure-test/bazel/test/test.yaml

==================================
====== Test file: test.yaml ======
==================================
=== RUN: Metadata Test
--- FAIL
duration: 0s
Error: error creating driver: processing tar image reference: mkdir C:\Users\Alex\AppData\Local\Temp\C:usersalexdocumentsgithubcontainer-structure-testbazeltesttarball.tar@sha256:1e7e2b9f2239dada4f655b859ebd6faea211af04aeb0a98ef40e47f7996474761649877104: The filename, directory name, or volume label syntax is incorrect.
```

Traced this down to the call here which constructs that long path and fails to `mkdir`:
https://github.com/GoogleContainerTools/container-diff/blob/v0.17.0/pkg/util/image_utils.go#L198
via https://github.com/GoogleContainerTools/container-diff/blob/v0.17.0/pkg/util/image_utils.go#L163
via https://github.com/GoogleContainerTools/container-structure-test/blob/v1.15.0/pkg/drivers/tar_driver.go#L40

I think this should do some more work to sanitize and shorten the name. As one proposal, we could just construct a hash of the name to make the tmpdir.

### Information

- container-diff version: 0.17.0 (based on https://github.com/GoogleContainerTools/container-structure-test/blob/v1.15.0/go.mod#L6)
- Operating system: Windows!

### Steps to reproduce the behavior

1. Clone https://github.com/GoogleContainerTools/container-structure-test on windows
2. `cd bazel/test`
3. `bazel test ...` and see the failure above

### PR DESCRIPTION
**Pull request by alexeagle**
Fixes #394

### CODE REVIEW

**Comment by alexeagle** [comment]
Note @nkubala @dlorenc this was added in https://github.com/GoogleContainerTools/container-diff/pull/232, here's the spot https://github.com/GoogleContainerTools/container-diff/commit/0be9c4131abb391c02cf1634baf4939ea3d9ac91#diff-ab967ab1a2f3a1b769106eeb7bfe892ef0e81d1d27811fa15be08e6749feee1fR263
I don't see any code review discussion about it, so I don't know if there's a reason you chose to make the TempDir have such a descriptive name. I imagine it was for debugging?

**Comment by loosebazooka** [comment]
@briandealwis maybe?

**Comment by alexeagle** [comment]
Another note, even on non-Windows platforms this code frequently causes errors due to creating paths that are too long for the underlying filesystem.

**Comment by dlorenc** [comment]
LGTM :)

**Comment by alexeagle** [comment]
@tequilarista maybe? You merged the most recent commit on HEAD

**Comment by alexeagle** [comment]
@gabyx @nkubala could one of you merge this pls?

**Comment by dlorenc** [comment]
I think it's @loosebazooka

**Review by loosebazooka — APPROVED** [review]

**Pull request merged**
